//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitapSatisVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetayliKitapBilgisi
    {
        public int KitapID { get; set; }
        public int saticiID { get; set; }
        public string saticiad { get; set; }
        public string KitapAd { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public Nullable<int> Adet { get; set; }
        public string imgpath { get; set; }
        public string kategadi { get; set; }
        public string altkatadi { get; set; }
        public string yazaradi { get; set; }
        public int KategoriID { get; set; }
        public int AltKategoriID { get; set; }
    }
}
