//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitapSatisVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KargoFirmYetkili
    {
        public int YetkiliID { get; set; }
        public string YetkiliAd { get; set; }
        public int KargoFirmasiID { get; set; }
    
        public virtual KargoFirmasi KargoFirmasi { get; set; }
    }
}
