//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitapSatisVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kart()
        {
            this.Siparis = new HashSet<Siparis>();
        }
    
        public int KartID { get; set; }
        public string KartNumarası { get; set; }
        public int UserID { get; set; }
        public string KartınUstundekiİsim { get; set; }
        public string CVV { get; set; }
        public int sonKullAy { get; set; }
        public int sonKullYil { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparis> Siparis { get; set; }
    }
}
