//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitapSatisVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.KitapSiparisEdilir = new HashSet<KitapSiparisEdilir>();
            this.KitapYaz = new HashSet<KitapYaz>();
        }
    
        public int KitapID { get; set; }
        public string KitapAdi { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public int KategoriID { get; set; }
        public int AltKategoriID { get; set; }
        public int SaticiID { get; set; }
        public string imgPath { get; set; }
        public int Adet { get; set; }
    
        public virtual AltKategori AltKategori { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapSiparisEdilir> KitapSiparisEdilir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapYaz> KitapYaz { get; set; }
    }
}
