//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitapSatisVol1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class İkinciElKitapSatisEntities1 : DbContext
    {
        public İkinciElKitapSatisEntities1()
            : base("name=İkinciElKitapSatisEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AltKategori> AltKategori { get; set; }
        public virtual DbSet<Fatura> Fatura { get; set; }
        public virtual DbSet<il> il { get; set; }
        public virtual DbSet<ilce> ilce { get; set; }
        public virtual DbSet<KargoFirmasi> KargoFirmasi { get; set; }
        public virtual DbSet<KargoFirmYetkili> KargoFirmYetkili { get; set; }
        public virtual DbSet<Kart> Kart { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kitap> Kitap { get; set; }
        public virtual DbSet<KitapSiparisEdilir> KitapSiparisEdilir { get; set; }
        public virtual DbSet<KitapYaz> KitapYaz { get; set; }
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Users_UserTurleriIliskisi> Users_UserTurleriIliskisi { get; set; }
        public virtual DbSet<UserTurleri> UserTurleri { get; set; }
        public virtual DbSet<Yazar> Yazar { get; set; }
        public virtual DbSet<detayliAdminListesi> detayliAdminListesi { get; set; }
        public virtual DbSet<DetayliKitapBilgisi> DetayliKitapBilgisi { get; set; }
        public virtual DbSet<detayliMusteriListesi> detayliMusteriListesi { get; set; }
        public virtual DbSet<detayliSaticiListesi> detayliSaticiListesi { get; set; }
        public virtual DbSet<KisiyeGoreTurListesiView> KisiyeGoreTurListesiView { get; set; }
        public virtual DbSet<saticiListesi> saticiListesi { get; set; }
        public virtual DbSet<SiparişDetayı> SiparişDetayı { get; set; }
    
        public virtual ObjectResult<Nullable<int>> KisiyeGoreTurListesi(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("KisiyeGoreTurListesi", idParameter);
        }
    }
}
