//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitapSatisVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.Fatura = new HashSet<Fatura>();
            this.KitapSiparisEdilir = new HashSet<KitapSiparisEdilir>();
        }
    
        public int SiparisID { get; set; }
        public System.DateTime SipTarihi { get; set; }
        public int MusteriID { get; set; }
        public int KargoFirmasiID { get; set; }
        public int MusteriKartID { get; set; }
        public decimal ToplamTutar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura> Fatura { get; set; }
        public virtual KargoFirmasi KargoFirmasi { get; set; }
        public virtual Kart Kart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapSiparisEdilir> KitapSiparisEdilir { get; set; }
        public virtual Users Users { get; set; }
    }
}
