//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitapSatisVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparişDetayı
    {
        public int SiparisID { get; set; }
        public int ID { get; set; }
        public string KitapAdi { get; set; }
        public int UrunAdedi { get; set; }
        public decimal BirimFiyat { get; set; }
        public string KargoFirmasiAdi { get; set; }
        public string KargoFirmasiTel { get; set; }
        public string YetkiliAd { get; set; }
        public string Musteri { get; set; }
        public string Adres { get; set; }
        public int ilceKodu { get; set; }
        public int ilKodu { get; set; }
        public string satici { get; set; }
        public int SaticiID { get; set; }
        public System.DateTime SipTarihi { get; set; }
    }
}
