//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitapSatisVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTurleri()
        {
            this.Users_UserTurleriIliskisi = new HashSet<Users_UserTurleriIliskisi>();
        }
    
        public int TurID { get; set; }
        public string UserTurAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users_UserTurleriIliskisi> Users_UserTurleriIliskisi { get; set; }
    }
}
