//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İkinciElKitapSatisVol1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_UserTurleriIliskisi
    {
        public int ID { get; set; }
        public int UsersID { get; set; }
        public int TurID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual UserTurleri UserTurleri { get; set; }
    }
}
